### PR TITLE
Years of experience and portfolio link on Intern SignUp

### PR DESCRIPTION
**Pull request by habitual4laif**
Test link

http://hngi7.hng.tech/join-intern.php

http://hngi7.hng.tech/registered_interns.php

### CODE REVIEW

**Comment by phiiileo** [comment]
what exactly did you do?

**Comment by habitual4laif** [comment]
I removed the years of experience & link to portfolio from the form, admin (View page), controller, model & database.

Then I also filter the interest field on the form to restrict it to the present track available in the internship

**Comment by phiiileo** [comment]
Now, you have a conflict...hmmmm

**Comment by phiiileo** [comment]
Hope your repo and resolve conflicts, Thanks

**Comment by habitual4laif** [comment]
Conflict resolved and another PR sent

**Pull request closed without merging**
